### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by andrewliii** [andrewliii/discord#1]
**Unhandled promise rejection**. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:99066) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ShaneLee** [comment]
Hi Andrew, 

Put in a PR to help you fix this. 


Shane
